"""add avatar_url to users

Revision ID: bd18a523ba16
Revises: 
Create Date: 2026-05-04 14:17:42.912470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd18a523ba16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('processed_payments_stripe_session_id_key', 'processed_payments', type_='unique')
    op.drop_index('ix_processed_payments_stripe_session_id', table_name='processed_payments')
    op.create_index(op.f('ix_processed_payments_stripe_session_id'), 'processed_payments', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_processed_payments_user_id'), 'processed_payments', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"notifications": true}\'::jsonb'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"notifications": true}\'::jsonb'))
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_processed_payments_user_id'), table_name='processed_payments')
    op.drop_index(op.f('ix_processed_payments_stripe_session_id'), table_name='processed_payments')
    op.create_index('ix_processed_payments_stripe_session_id', 'processed_payments', ['stripe_session_id'], unique=False)
    op.create_unique_constraint('processed_payments_stripe_session_id_key', 'processed_payments', ['stripe_session_id'])
    # ### end Alembic commands ###
